server:
  port: 8081

spring:
  application:
    name: API-GATEWAY
zuul:
  routes:
    book:
      path: /book/**
      sensitiveHeaders:
      stripPrefix: true
      url: http://127.0.0.1:8082


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    registerWithEureka: true